config/routes.rb
ProTemplateApp::Application.routes.draw do
  resources :blog_entries

  devise_for :users

  root :to => "home#index"
end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  validates_presence_of :subject
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_filter :authenticate_user!
  # GET /blog_entries
  # GET /blog_entries.xml
  def index
    @blog_entries = BlogEntry.paginate :page => params[:page], :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blog_entries }
    end
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.xml
  def show
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/new
  # GET /blog_entries/new.xml
  def new
    @blog_entry = BlogEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/1/edit
  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  # POST /blog_entries
  # POST /blog_entries.xml
  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully created.') }
        format.xml  { render :xml => @blog_entry, :status => :created, :location => @blog_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_entries/1
  # PUT /blog_entries/1.xml
  def update
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      if @blog_entry.update_attributes(params[:blog_entry])
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.xml
  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to(blog_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog_entries/_form.html.haml
.group
  = f.label :subject, t("activerecord.attributes.blog_entry.subject", :default => "Subject"), :class => :label
  = f.text_field :subject, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :content, t("activerecord.attributes.blog_entry.content", :default => "Content"), :class => :label
  = f.text_area :content, :class => 'text_area'
  %span.description Ex: a simple text
.group
  = f.label :publish_at, t("activerecord.attributes.blog_entry.publish_at", :default => "Publish at"), :class => :label
  = f.datetime_select :publish_at, :class => 'datetime_select'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), blog_entries_path, :class => "text_button_padding link_button"

app/views/blog_entries/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/blog_entries/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Blog Entry
    .inner
      = form_for @blog_entry, :url => blog_entry_path(@blog_entry), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/blog_entries/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Blog Entries
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.blog_entry.subject", :default => t("activerecord.labels.subject", :default => "Subject"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @blog_entries.each do |blog_entry|
          %tr{:class => cycle("odd", "even")}
            %td
              = blog_entry.id
            %td
              = link_to blog_entry.subject, blog_entry_path(blog_entry)
            %td
              = blog_entry.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", blog_entry_path(blog_entry)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blog_entry_path(blog_entry)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", blog_entry_path(blog_entry), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = will_paginate @blog_entries
- content_for :sidebar, render(:partial => 'sidebar')

app/views/blog_entries/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Blog Entry
    .inner
      = form_for :blog_entry, :url => blog_entries_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/blog_entries/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", blog_entries_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_blog_entry_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", blog_entry_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.blog_entry.subject", :default => t("activerecord.labels.subject", :default => "Subject"))
          \:
        = @blog_entry.subject
      %p
        %b
          = t("activerecord.attributes.blog_entry.content", :default => t("activerecord.labels.content", :default => "Content"))
          \:
        = @blog_entry.content
      %p
        %b
          = t("activerecord.attributes.blog_entry.publish_at", :default => t("activerecord.labels.publish_at", :default => "Publish at"))
          \:
        = @blog_entry.publish_at
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_blog_entry_path(@blog_entry), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), blog_entry_path(@blog_entry), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/home/index.html.haml
.block#text
  .content
    %h2 Home
    .inner
      %p.first Please use the navigation bar above to move around the site.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title My Latest Web App
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true
    = javascript_include_tag :defaults, :cache => true
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          %a{:href => "/"} My Latest Web App
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              = link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path
        #main-navigation
          %ul.wat-cf
            %li{ :class => (params[:controller] == "home" ? "first active" : "first") }
              = link_to "Home", root_path
            %li{ :class => (params[:controller] == "blog_entries" ? "active" : nil) }
              = link_to "Blog Entries", blog_entries_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p
                Copyright &copy; #{Time.now.year} My Latest Web App.
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %title My Latest Web App
    = stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true
    = csrf_meta_tag
  %body
    #container
      #box
        = yield